### ISSUE TITLE
Able to define environments within environments

### ISSUE THREAD

**Issue by hagbarddenstore** [hagbarddenstore/buldep#1]
The `environments` part of the `.buldep` file would look something like this:

```yaml
environments:
  variables:
    name: Buldep
  us-east-1:
    variables:
      region: us-east-1
    environments:
      development:
        variables:
          environment: development
      testing:
        variables:
          environment: testing
      staging:
        variables:
          environment: staging
      production:
        variables:
          environment: production
```

This allows an environment to inherit the variables from the parent environment, thus reducing redundant variables.
