### ISSUE TITLE
Able to declare a condition when a pipeline should be executed

### ISSUE THREAD

**Issue by hagbarddenstore** [hagbarddenstore/buldep#2]
Example `environments` declaration in `.buldep` file:

```yaml
environments:
  development:
    when:
      branch: master
  testing:
    when:
      branch: master
  staging:
    when:
      branch: release
  production:
    when:
      branch: release
```
